### ISSUE TITLE
add to awesome list

### ISSUE THREAD

**Issue by dereuromark** [rrd108/cakephp-datalist#1]
You should add it to https://github.com/FriendsOfCake/awesome-cakephp#templating

**Comment by rrd108** [comment]
That is a good idea, but the contribution guidelines says:

> Proposed libraries should ideally have 10+ stars.

The plugin did not reached it yet. 

Anyway I send it, let see :) Thanks.

**Comment by dereuromark** [comment]
I would say that if you add a test case for your helper, you make up for it just fine :)

I like your good documentation and it adds a new value that has not been supported yet.
So I think even now already this can be beneficial for some people.

**Comment by dereuromark** [comment]
Would also be nice to add some travis and CO badges into the readme. To quickly see the tests are green ec.

I will close this now.

**Comment by rrd108** [comment]
See suggestions here: https://github.com/FriendsOfCake/awesome-cakephp/pull/305#issuecomment-404191644

**Comment by rrd108** [comment]
this might help for CO: https://github.com/FriendsOfCake/travis
and add download badge also

**Comment by rrd108** [comment]
add fixtures and test with models

**Comment by dereuromark** [comment]
Since you are also supporting 3.5 ( "cakephp/cakephp": "^3.5" )
I suggest also prefer lowest BC check as per https://www.dereuromark.de/2018/03/14/cakephp-3-6-is-coming/#prepare-your-plugins

**Comment by rrd108** [comment]
fixed by 00f1a89ae4d5022b53b0540df673fd9a84fef2cc
