### ISSUE TITLE
separate auto-save functionality

### ISSUE THREAD

**Issue by dereuromark** [rrd108/cakephp-datalist#2]
I was curious and looked into your plugin yesterday evening.

Why not having two:
- Plain `DatalistWidget` (just like normal select)
- `DatalistJsWidget` etc with JS (and maybe even JS fallback for non supportive browsers = shim) for your additional functionality?

I also found a few flaws in your code
The default value (when posting a form and it didnt validate) is lost on display.

Check my fixed version test:

        'datalist' => '<input type="text" id="{{id}}" name="{{name}}" list="datalist-{{id}}" autocomplete="off"{{inputAttrs}}><datalist id="datalist-{{id}}"{{datalistAttrs}}>{{content}}</datalist>',

and 

        $default = isset($data['val']) ? $data['val'] : null;
        unset(...);

        $inputData['value'] = $default;
        $inputAttrs = $this->_templates->formatAttributes($inputData);

        $datalistAttrs = $this->_templates->formatAttributes($data);
        return $this->_templates->format(
            'datalist',
            [
                'name' => $name,
                'inputAttrs' => $inputAttrs,
                'datalistAttrs' => $datalistAttrs,
                'content' => implode('', $options),
                'id' => $data['id'],
            ]
        );

Also, no constructor overwrite needed, or interface implement (parent does that).

**Comment by rrd108** [comment]
I was originally thinking to have a plain datalist widget, but as in all browser they show the options' ids it is really ugly.
Anyway I can make the js optional, I just have to think a little about.

Thanks for pointing on the flaws, I will fix them.

**Comment by dereuromark** [comment]
You are right
But a config key "keys" true/false could opt in key vs value usage:

    if (!$data['keys']) {
            $options = str_replace(
                'value',
                'data-value',
                $options
            );
        }

I can also add this to my Tools plugin, if you want to keep yours JS enriched by default.

**Comment by rrd108** [comment]
No, I will use the plain as the default.

**Comment by dereuromark** [comment]
Refs https://github.com/dereuromark/cakephp-tools/blob/master/docs/Widget/Datalist.md

**Comment by rrd108** [comment]
@dereuromark if youput the code into your tools plugn I would completely get rid of the plain datalist in my code and I would just extend your implementation with the JS extended datalist.

For that I would need a new release on your side.

**Comment by dereuromark** [comment]
I wouldnt make it a dependency. Just keep your "enhanced" one. That should be fine.
You can use some of the test cases maybe via copy and paste.
