### ISSUE TITLE
Unexpected field in POST data,

### ISSUE THREAD

**Issue by ealfonsov89** [rrd108/cakephp-datalist#3]
hi, i have an security exception that say "Unexpected field '\__address.street_id' in POST data" i know that happens because the plugin add an extra input with "__" name, when i do the submit the inputs still exist, and the security component send the exception.

**Comment by ealfonsov89** [comment]
i temporarily resolve it adding this to the view of my controller action
```
<?= $this->Html->scriptStart(['block' => true,'type'=>'text/javascript', 'language'=>'javascript']); ?>
$(document).ready(function () {
    $('input[list][id^=__]', $('form')).each(function (index, item){
        $(item).attr("disabled", false);
    });
    $('form').submit(function (e){
        $('input[list][id^=__]', $(this)).each(function (index, item){
            $(item).attr("disabled", true);
        });
        return true;
    });
})
<?= $this->Html->scriptEnd(); ?> 
```

**Comment by rrd108** [comment]
Is the exception droped by `SecurityComponent`?

**Comment by ealfonsov89** [comment]
yes, sorry the (__)do not show on github code label, i fixed now

**Comment by rrd108** [comment]
I will try to reproduce the error and get back to you

**Comment by ealfonsov89** [comment]
I'm using CakePHP 3.6 with ACL and csrf middleware added on src/Application.php

**Comment by ealfonsov89** [comment]
you need that part of the form?

**Comment by ealfonsov89** [comment]
when i comment 

> $this->loadComponent('Security');

 in AppController it works

**Comment by rrd108** [comment]
One thing waht security component does is checking if any new input fileds added to the generated html form and deny the request if it happened.
As the plugin inserts new inputs it will fail.

I can do to insert inputs at the client side to solve this problem, but till that you wil not able to use the plugin with security enabled.

**Comment by ealfonsov89** [comment]
it work with the script but i use jquery
